### PR TITLE
Update to 0.17

### PR DESCRIPTION
**Pull request by Jelmergu**
Add thumbnail (taken from mod portal)

Signed-off-by: Jelmergu <github@jelmerwijnja.nl>

### CODE REVIEW

**Comment by Cogito** [comment]
Looks straightforward enough, what's the reasoning behind changing the default shortcut? Clash with a built-in shortcut or something else?

**Comment by Jelmergu** [comment]
When I went to test the mod, the mod didn't react to Alt+ R anymore, a quick look into the control mapping told me that the mod was listening for Alt + 'missing'. Affter I changed the lowercase 'r' to uppercase 'R' it worked again.

Might have been because of [this](https://forums.factorio.com/viewtopic.php?f=7&t=65881) though

**Comment by Jelmergu** [comment]
Any indication when the PR will be merged?

**Comment by Cogito** [comment]
sorry, totally forgot to merge! will publish now

**Pull request merged**
