### PR TITLE
Update to Factorio version 0.16

### PR DESCRIPTION
**Pull request by Jelmergu**
Signed-off-by: Jelmergu <jelmergu@gmail.com>

### CODE REVIEW

**Comment by Jelmergu** [comment]
Noticed something strange with factorio version in json

**Comment by Cogito** [comment]
Have you had a chance to test yet?

I wasn't able to even boot into 16.1 yesterday, I think 16.2 fixed that issue though.

I've also been in discussion with @Nexela as there are some scripting changes in the update that should make some of the code much simpler.

Something along the lines of this should work, apparently (untested)
```LUA
local function reverse_transport_entity(belt, direction)
    if belt.type == "loader" or (belt.type == "underground-belt" and belt.belt_to_ground_type == "input") then
        belt.rotate()
    else
        belt.direction = direction
        belt_lines.flip(belt)
    end
end
```

**Comment by Jelmergu** [comment]
I have tested it with an empty belt. Just thought of the fact that I should also do so with an filled belt.
I'll have a look at that simplere method. I am however not that good yet with the Factorio modding API.

**Comment by Jelmergu** [comment]
I have now tested the current way with a partly filled belt and a full belt. both ways are working as expected

**Comment by Jelmergu** [comment]
When trying the alternate way, it seems that 
```lua
function M.flipBeltLines(belt)
    if belt.type == "loader" or (belt.type == "underground-belt" and belt.belt_to_ground_type == "input") then
        belt.rotate()
    elseif belt.type == "transport-belt" then
        belt.rotate()
        belt.rotate()
    end
end
```
seems to be able to almost replace the complete contents of `flipBeltLines.lua`. The only problem at the moment are the corners, which I will have a look at.
I know it is not suprising that the corners don't work as I rotate the belt twice

**Comment by Cogito** [comment]
Ok fantastic, we'll need to test multiple lengths of belt, and connected with undergrounds/splitters/loaders etc but hopefully most of that works still.

I haven't looked in to how much the optimisations would affect the reversing, which is my main concern, but my guess is that it will be fine.

Biggest potential issue is the logic to find the next belt up or downstream. At the moment it assumes it is just looking one tile in the direction it is pointing, so as long as that hasn't changed then should be good.

Also, happy to get the simple update out with compatibility (as long as it works), and then we can simplify the code where possible afterwards.

**Comment by Jelmergu** [comment]
I'd say make a new branch for it and as long as it isn't done use the version in this PR

I did find a way to completely rotate the belt and underground belt using the rotate with correct cornering. If you make a new branch I'll make a new PR to it. It isn't done yet as the items on the belt stay on the same lane, whereas the current version will put them on the other lane.

**Pull request merged**
